apiVersion: apps/v1
kind: Deployment
metadata:
    name: model
    namespace: web
spec:
    replicas: 1
    selector:
        matchLabels:
            app: model
    template:
        metadata:
            labels:
                app: model
        spec:
            containers:
                - name: model
                  image: ghcr.io/false-ltd/model:latest
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 3000
                  env:
                      - name: NUXT_PUBLIC_SUPABASE_URL
                        valueFrom:
                            secretKeyRef:
                                name: model-secret
                                key: SUPABASE_URL
                      - name: NUXT_PUBLIC_SUPABASE_KEY
                        valueFrom:
                            secretKeyRef:
                                name: model-secret
                                key: SUPABASE_KEY
                  resources:
                      requests:
                          memory: "128Mi"
                          cpu: "100m"
                      limits:
                          memory: "512Mi"
                          cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
    name: model
    namespace: web
spec:
    selector:
        app: model
    ports:
        - port: 80
          targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: model
    namespace: web
    annotations:
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
        cert-manager.io/cluster-issuer: "letsencrypt"
spec:
    ingressClassName: nginx
    tls:
        - hosts:
              - model.false.ltd
          secretName: model-app-tls
    rules:
        - host: model.false.ltd
          http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: model-app
                            port:
                                number: 80
