apiVersion: apps/v1
kind: Deployment
metadata:
    name: model
    namespace: web
spec:
    replicas: 1
    selector:
        matchLabels:
            app: model
    template:
        metadata:
            labels:
                app: model
        spec:
            containers:
                - name: model
                  image: ghcr.io/false-ltd/model:latest
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 80
                  resources:
                      requests:
                          memory: "32Mi"
                          cpu: "50m"
                      limits:
                          memory: "64Mi"
                          cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
    name: model
    namespace: web
spec:
    selector:
        app: model
    ports:
        - port: 80
          targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: model
    namespace: web
    annotations:
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
        cert-manager.io/cluster-issuer: "letsencrypt"
spec:
    ingressClassName: nginx
    tls:
        - hosts:
              - model.false.ltd
          secretName: model-tls
    rules:
        - host: model.false.ltd
          http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: model-tls
                            port:
                                number: 80
