CREATE TABLE IF NOT EXISTS providers (
    id          BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '自增主键',
    provider_id VARCHAR(100)  NOT NULL UNIQUE               COMMENT '服务商标识，如 openai, anthropic',
    name        VARCHAR(255)  NOT NULL                       COMMENT '服务商显示名称',
    npm         VARCHAR(255)  NOT NULL DEFAULT ''            COMMENT 'AI SDK NPM 包名',
    env         JSON          NOT NULL                       COMMENT '环境变量 key 数组，如 ["OPENAI_API_KEY"]',
    doc_url     VARCHAR(512)  DEFAULT ''                     COMMENT '文档链接地址',
    api_url     VARCHAR(512)  DEFAULT ''                     COMMENT 'OpenAI 兼容 API 端点',
    synced_at   DATETIME      DEFAULT NULL                   COMMENT '最后一次数据同步时间',
    created_at  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
    updated_at  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间',
    INDEX idx_providers_synced_at (synced_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI 服务商信息表';

CREATE TABLE IF NOT EXISTS models (
    id                 BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY  COMMENT '自增主键',
    model_id           VARCHAR(255)   NOT NULL               COMMENT '模型唯一标识，如 gpt-4o',
    provider_id        VARCHAR(100)   NOT NULL               COMMENT '关联服务商 ID，对应 providers.provider_id',
    name               VARCHAR(255)   NOT NULL                      COMMENT '模型显示名称',
    family             VARCHAR(100)   DEFAULT ''                    COMMENT '模型家族分组，如 gpt-4',
    attachment         TINYINT(1)     NOT NULL DEFAULT 0            COMMENT '是否支持文件附件',
    reasoning          TINYINT(1)     NOT NULL DEFAULT 0            COMMENT '是否支持推理/思维链',
    tool_call          TINYINT(1)     NOT NULL DEFAULT 0            COMMENT '是否支持工具调用',
    structured_output  TINYINT(1)     DEFAULT NULL                  COMMENT '是否支持结构化输出',
    temperature        TINYINT(1)     NOT NULL DEFAULT 1            COMMENT '是否支持温度参数调节',
    knowledge          VARCHAR(50)    DEFAULT ''                    COMMENT '知识截止日期，格式 YYYY-MM 或 YYYY-MM-DD',
    release_date       VARCHAR(50)    DEFAULT ''                    COMMENT '首次公开发布日期',
    last_updated       VARCHAR(50)    DEFAULT ''                    COMMENT '最近一次更新日期',
    open_weights       TINYINT(1)     NOT NULL DEFAULT 0            COMMENT '模型权重是否公开可用',
    status             VARCHAR(20)    DEFAULT NULL                  COMMENT '模型状态：alpha / beta / deprecated',
    interleaved        JSON           DEFAULT NULL                  COMMENT '交错推理支持配置',
    modalities_input   JSON           DEFAULT NULL                  COMMENT '输入模态数组，如 ["text","image"]',
    modalities_output  JSON           DEFAULT NULL                  COMMENT '输出模态数组，如 ["text"]',
    cost_input         DECIMAL(10,4)  DEFAULT NULL                  COMMENT '每百万输入 token 成本（USD）',
    cost_output        DECIMAL(10,4)  DEFAULT NULL                  COMMENT '每百万输出 token 成本（USD）',
    cost_reasoning     DECIMAL(10,4)  DEFAULT NULL                  COMMENT '每百万推理 token 成本（USD）',
    cost_cache_read    DECIMAL(10,4)  DEFAULT NULL                  COMMENT '每百万缓存读取 token 成本（USD）',
    cost_cache_write   DECIMAL(10,4)  DEFAULT NULL                  COMMENT '每百万缓存写入 token 成本（USD）',
    cost_input_audio   DECIMAL(10,4)  DEFAULT NULL                  COMMENT '每百万音频输入 token 成本（USD）',
    cost_output_audio  DECIMAL(10,4)  DEFAULT NULL                  COMMENT '每百万音频输出 token 成本（USD）',
    limit_context      INT            DEFAULT NULL                  COMMENT '最大上下文窗口大小（token 数）',
    limit_input        INT            DEFAULT NULL                  COMMENT '最大输入 token 数',
    limit_output       INT            DEFAULT NULL                  COMMENT '最大输出 token 数',
    created_at         DATETIME       NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
    updated_at         DATETIME       NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间',
    UNIQUE KEY uk_model_provider (model_id, provider_id),
    INDEX idx_models_family (family),
    INDEX idx_models_cost_input (cost_input),
    INDEX idx_models_context (limit_context),
    INDEX idx_models_reasoning (reasoning),
    INDEX idx_models_open_weights (open_weights)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI 模型信息表';
