// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/compare": {
            "get": {
                "description": "根据多个模型 ID 返回对比数据，保持请求顺序",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "compare"
                ],
                "summary": "模型对比",
                "parameters": [
                    {
                        "type": "string",
                        "description": "模型 ID，逗号分隔 (如 1,2,3)",
                        "name": "ids",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_false-ltd_models-api_internal_model.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/models": {
            "get": {
                "description": "分页查询 AI 模型，支持筛选、排序",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "models"
                ],
                "summary": "获取模型列表",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 100,
                        "description": "每页数量",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "名称搜索",
                        "name": "q",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "name",
                        "description": "排序字段 (name/cost_input/cost_output/limit_context/release_date)",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "asc",
                        "description": "排序方向 (asc/desc)",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "服务商过滤，逗号分隔",
                        "name": "providers",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "输入模态过滤，逗号分隔",
                        "name": "input_types",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "输出模态过滤，逗号分隔",
                        "name": "output_types",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "仅推理模型",
                        "name": "reasoning",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "仅工具调用模型",
                        "name": "tool_call",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "仅视觉模型",
                        "name": "vision",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "仅支持附件的模型",
                        "name": "attachment",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "仅免费模型",
                        "name": "free_only",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "输入成本低于 $1",
                        "name": "under_1",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "最低输入成本",
                        "name": "price_min",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "最高输入成本",
                        "name": "price_max",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_false-ltd_models-api_internal_model.PagedResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_false-ltd_models-api_internal_model.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/models/{id}": {
            "get": {
                "description": "根据 ID 获取单个模型详情（含服务商信息）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "models"
                ],
                "summary": "获取模型详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "模型 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_false-ltd_models-api_internal_model.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_false-ltd_models-api_internal_model.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_false-ltd_models-api_internal_model.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/providers": {
            "get": {
                "description": "返回所有 AI 服务商及其模型数量",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "providers"
                ],
                "summary": "获取服务商列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_false-ltd_models-api_internal_model.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/stats": {
            "get": {
                "description": "返回 KPI、分层分布、能力统计、模态分布等综合统计",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stats"
                ],
                "summary": "获取统计数据",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_false-ltd_models-api_internal_model.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_false-ltd_models-api_internal_model.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/sync": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "从 models.dev 拉取最新数据，10 分钟内不会重复同步",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sync"
                ],
                "summary": "触发数据同步",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_false-ltd_models-api_internal_model.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_false-ltd_models-api_internal_model.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_false-ltd_models-api_internal_model.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/sync/status": {
            "get": {
                "description": "返回最近一次同步时间",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sync"
                ],
                "summary": "查看同步状态",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_false-ltd_models-api_internal_model.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_false-ltd_models-api_internal_model.Response"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "检查服务是否正常运行",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "健康检查",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_false-ltd_models-api_internal_model.PageMeta": {
            "type": "object",
            "properties": {
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                }
            }
        },
        "github_com_false-ltd_models-api_internal_model.PagedResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "message": {
                    "type": "string"
                },
                "meta": {
                    "$ref": "#/definitions/github_com_false-ltd_models-api_internal_model.PageMeta"
                }
            }
        },
        "github_com_false-ltd_models-api_internal_model.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Models API",
	Description:      "AI 模型数据聚合服务，从 models.dev 同步数据并提供 RESTful API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
